name: Pipeline

on: push

jobs:
  megalinter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: oxsecurity/megalinter@v8
  nix-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Nix-Info
      run: nix-shell -p nix-info --run "nix-info -m"
    - name: Deadnix
      run: nix-shell -p deadnix --run "deadnix --fail"
    - name: Statix
      run: nix-shell -p statix --run "statix check"
